### ISSUE TITLE
add deployment agent

### ISSUE THREAD

**Issue by wsky** [chemao/auto-deploy#5]
ADP ---> agent at real server

we could not execute shell at remote server in production environment, so we need a agent to do this

after that, sls log will be a problem, all log render to a single file currently, should be splited

```
$app-$timestamp.log
```
change to, maybe like this
```
/$app-$timestamp
    - $IP.log
    - $IP.log
```

**Comment by mfmelody** [comment]
use ssh remotely in script so close this issue temporarily
